load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library") 

go_library(
  name = "calc",
  srcs = [
      "calc.go",
  ],
  importpath = "bazel-go/calc",
  visibility = ["//visibility:public"],
  # deps = ["//calc"],
)
